export const SHOP_DATA = [
  {
    name: "Brown Brim",
    category: "Hats",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/ZYW3VTp/brown-brim.png",
    price: 25,
  },
  {
    name: "Blue Beanie",
    category: "Hats",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
    price: 18,
  },
  {
    name: "Brown Cowboy",
    category: "Hats",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/QdJwgmp/brown-cowboy.png",
    price: 35,
  },
  {
    name: "Grey Brim",
    category: "Hats",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/RjBLWxB/grey-brim.png",
    price: 25,
  },
  {
    name: "Green Beanie",
    category: "Hats",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/YTjW3vF/green-beanie.png",
    price: 18,
  },
  {
    name: "Palm Tree Cap",
    category: "Hats",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/rKBDvJX/palm-tree-cap.png",
    price: 14,
  },
  {
    name: "Red Beanie",
    category: "Hats",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/bLB646Z/red-beanie.png",
    price: 18,
  },
  {
    name: "Wolf Cap",
    category: "Hats",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/1f2nWMM/wolf-cap.png",
    price: 14,
  },
  {
    name: "Blue Snapback",
    category: "Hats",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/X2VJP2W/blue-snapback.png",
    price: 16,
  },
  {
    name: "Adidas NMD",
    category: "Sneakers",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/0s3pdnc/adidas-nmd.png",
    price: 220,
  },
  {
    name: "Adidas Yeezy",
    category: "Sneakers",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/dJbG1cT/yeezy.png",
    price: 280,
  },
  {
    name: "Black Converse",
    category: "Sneakers",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/bPmVXyP/black-converse.png",
    price: 110,
  },
  {
    name: "Nike White AirForce",
    category: "Sneakers",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/1RcFPk0/white-nike-high-tops.png",
    price: 160,
  },
  {
    name: "Nike Red High Tops",
    category: "Sneakers",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/QcvzydB/nikes-red.png",
    price: 160,
  },
  {
    name: "Nike Brown High Tops",
    category: "Sneakers",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/fMTV342/nike-brown.png",
    price: 160,
  },
  {
    name: "Air Jordan Limited",
    category: "Sneakers",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/w4k6Ws9/nike-funky.png",
    price: 190,
  },
  {
    name: "Timberlands",
    category: "Sneakers",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/Mhh6wBg/timberlands.png",
    price: 200,
  },
  {
    name: "Black Jean Shearling",
    category: "Jackets",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/XzcwL5s/black-shearling.png",
    price: 125,
  },
  {
    name: "Blue Jean Jacket",
    category: "Jackets",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/mJS6vz0/blue-jean-jacket.png",
    price: 90,
  },
  {
    name: "Grey Jean Jacket",
    category: "Jackets",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
    price: 90,
  },
  {
    name: "Brown Shearling",
    category: "Jackets",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/s96FpdP/brown-shearling.png",
    price: 165,
  },
  {
    name: "Tan Trench",
    category: "Jackets",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/M6hHc3F/brown-trench.png",
    price: 185,
  },
  {
    name: "Blue Tanktop",
    category: "Womens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/7CQVJNm/blue-tank.png",
    price: 25,
  },
  {
    name: "Floral Blouse",
    category: "Womens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/4W2DGKm/floral-blouse.png",
    price: 20,
  },
  {
    name: "Floral Dress",
    category: "Womens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/KV18Ysr/floral-skirt.png",
    price: 80,
  },
  {
    name: "Red Dots Dress",
    category: "Womens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png",
    price: 80,
  },
  {
    name: "Striped Sweater",
    category: "Womens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
    price: 45,
  },
  {
    name: "Yellow Track Suit",
    category: "Womens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
    price: 135,
  },
  {
    name: "White Blouse",
    category: "Womens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/qBcrsJg/white-vest.png",
    price: 20,
  },
  {
    name: "Camo Down Vest",
    category: "Mens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/xJS0T3Y/camo-vest.png",
    price: 325,
  },
  {
    name: "Floral T-shirt",
    category: "Mens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/qMQ75QZ/floral-shirt.png",
    price: 20,
  },
  {
    name: "Black & White Longsleeve",
    category: "Mens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/55z32tw/long-sleeve.png",
    price: 25,
  },
  {
    name: "Pink T-shirt",
    category: "Mens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/RvwnBL8/pink-shirt.png",
    price: 25,
  },
  {
    name: "Jean Long Sleeve",
    category: "Mens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png",
    price: 40,
  },
  {
    name: "Burgundy T-shirt",
    category: "Mens",
    description: "BLAH BLAH BLAH",
    quantity: 99,
    old_price: 99,
    image: "https://i.ibb.co/mh3VM1f/polka-dot-shirt.png",
    price: 25,
  },
];
